# Generated by Django 4.2.2 on 2023-06-26 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 16, 7, 45, 949894, tzinfo=datetime.timezone.utc)),
        ),
    ]
