version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management

    ports:
      - 5672:5672 #communication between the noes an CLI tool
      - 15672:15672 #communication with the management API
      - 556:556

    volumes:
      - .queue/data:/var/lib/rabbitmq/

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

    restart: always

volumes:
    logs-folder:
        name: ${log_rabbitmq_management}
        driver: local