# Generated by Django 4.0 on 2023-06-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_customuser_last_login_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
