# Generated by Django 4.0 on 2023-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_rename_name_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
    ]
