# Generated by Django 4.0 on 2023-06-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
