# Generated by Django 4.0 on 2023-06-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_remove_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ManyToManyField(to='proposals.CustomUser'),
        ),
    ]
