# Generated by Django 4.0 on 2023-06-18 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_remove_proposal_user_proposal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proposals.customuser'),
            preserve_default=False,
        ),
    ]
