# Generated by Django 4.2.2 on 2023-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CamposModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "obrigatorio",
                    models.BooleanField(
                        default=False,
                        verbose_name="Tornar este campo obrigatório em qualquer proposta",
                    ),
                ),
                (
                    "texto_ajuda",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unico",
                    models.BooleanField(
                        default=False, verbose_name="Tornar este um campo único"
                    ),
                ),
                ("ativo", models.BooleanField()),
            ],
            options={
                "verbose_name": "Campo",
                "verbose_name_plural": "Campos",
                "ordering": ["nome"],
            },
        ),
    ]
