# Generated by Django 4.2.2 on 2023-06-15 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camposmodel",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="camposmodel",
            name="obrigatorio",
            field=models.BooleanField(default=False, verbose_name="Campo obrigatório"),
        ),
        migrations.AlterField(
            model_name="camposmodel",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="camposmodel",
            name="unico",
            field=models.BooleanField(default=False, verbose_name="Campo único"),
        ),
        migrations.CreateModel(
            name="PropostasModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=13,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Valor da proposta",
                    ),
                ),
                ("ativa", models.BooleanField(default=True)),
                ("aprovada", models.BooleanField(default=False)),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de registro"
                    ),
                ),
                (
                    "data_avaliacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de avaliação"
                    ),
                ),
                (
                    "campos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propostas",
                        to="cadastros.camposmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta",
                "verbose_name_plural": "Propostas",
                "ordering": ["data_registro"],
            },
        ),
    ]
