# Generated by Django 4.2.2 on 2023-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_alter_camposmodel_ativo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propostasmodel",
            name="campos",
        ),
        migrations.AddField(
            model_name="propostasmodel",
            name="campos",
            field=models.ManyToManyField(
                related_name="campos_proposta",
                to="cadastros.camposmodel",
                verbose_name="Campos",
            ),
        ),
    ]
